name: online_cv
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utility
  http: ^1.2.2

  #state management
  flutter_riverpod: ^2.5.1

  #widget
  scroll_to_index: ^3.0.1 
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.0

  #multi language
  easy_localization: ^3.0.7
  country_flags: ^3.0.0


  #animation
  lottie: ^3.1.2

  #firebase
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0

  #design
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animation/
    - assets/translations/



